In [20]:
import torch
from datasets import load_from_disk

# Loading largest splits

train_dataset = load_from_disk("biggest_train")
val_dataset =load_from_disk("biggest_val")

Loading dataset from disk:   0%|          | 0/37 [00:00<?, ?it/s]

In [1]:

from datasets import load_from_disk

# Loading explicit datasets

#train_dataset = load_from_disk("exp_train")
#val_dataset =load_from_disk("exp_val")
test_dataset = load_from_disk("exp_test")

### Custom data collator

In [27]:
class DataCollatorSpeechSeq2SeqWithPadding:
    def __init__(self, label_pad_token_id: int = -100):
        self.processor = processor
        self.label_pad_token_id = label_pad_token_id

    def __call__(self, features):
        # Pad input features (audio)
        input_features = self.processor.feature_extractor.pad(
            [{"input_features": f["input_features"]} for f in features],
            return_tensors="pt"
        )

        # Prepare list of dicts with 'input_ids' for tokenizer.pad()
        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(
            label_features,
            return_tensors="pt",
            padding=True  # Explicitly set padding=True
        )

        # Extract padded input_ids and attention_mask
        labels = labels_batch["input_ids"]
        attention_mask = labels_batch.get("attention_mask", None)

        # Mask padding tokens with -100
        if attention_mask is not None:
            labels = labels.masked_fill(attention_mask.ne(1), self.label_pad_token_id)
        else:
            # Fallback: mask based on pad_token_id
            labels = labels.masked_fill(labels == self.processor.tokenizer.pad_token_id, self.label_pad_token_id)

        # Optional: remove BOS token if present at start for all sequences
        # Note: This might not be necessary for Speech2Text models
        if (
            self.processor.tokenizer.bos_token_id is not None and
            labels.size(1) > 0 and  # Check if we have any tokens
            (labels[:, 0] == self.processor.tokenizer.bos_token_id).all()
        ):
            labels = labels[:, 1:]

        # Return dict with keys matching model inputs
        batch = {
            "input_features": input_features["input_features"],
            "labels": labels
        }

        # Optional: Include attention_mask for labels if needed for generation
        # This can be useful for generation to know where real tokens end
        if attention_mask is not None and labels.size(1) > 0:
            # Adjust attention_mask if we removed BOS token
            if (
                self.processor.tokenizer.bos_token_id is not None and
                labels.size(1) == attention_mask.size(1) - 1
            ):
                attention_mask = attention_mask[:, 1:]
            # Don't include attention_mask in batch for now as it may confuse the model
            # batch["attention_mask"] = attention_mask

        return batch

In [4]:
!pip install -q jiwer

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [5]:
!pip install -q peft

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip

### Loading models from checkpoints

In [6]:
import os
from torch.utils.data import DataLoader
from torch.optim import AdamW
from transformers import get_scheduler
import torch
import numpy as np
import os
import shutil
import time
from tqdm.auto import tqdm

from peft import PeftModel
from transformers import Speech2TextForConditionalGeneration, Speech2TextProcessor


RESUME_FROM_CHECKPOINT = "imb_tuning/ex4/checkpoint-epoch29-wer0.7532-mer0.6842-1754437771"


if RESUME_FROM_CHECKPOINT and os.path.exists(RESUME_FROM_CHECKPOINT):
    print(f"=== LOADING FROM CHECKPOINT: {RESUME_FROM_CHECKPOINT} ===")

    # 1. Load base model
    base_model = Speech2TextForConditionalGeneration.from_pretrained("facebook/s2t-small-librispeech-asr")

    # 2. Load LoRA adapter from checkpoint
    model = PeftModel.from_pretrained(base_model, RESUME_FROM_CHECKPOINT)

    # 3. Move to device
    device = "cuda" if torch.cuda.is_available() else "mps"
    model.to(device)

    # 4. Debug: Check if adapter is loaded
    print("Available adapters:", model.peft_config.keys() if hasattr(model, 'peft_config') else "None")
    print("Active adapter:", getattr(model, 'active_adapter', 'None'))

    # 5. Set training mode (skip enable_adapters for now)
    model.train()

    # 6. Load processor
    processor = Speech2TextProcessor.from_pretrained(RESUME_FROM_CHECKPOINT)

    print("✓ Successfully loaded model and processor from checkpoint")

# Check trainable parameters without enable_adapters()
trainable_params = [p for p in model.parameters() if p.requires_grad]
print(f"Found {len(trainable_params)} trainable parameters")

# If no trainable parameters, manually enable LoRA params
if len(trainable_params) == 0:
    print("No trainable parameters found, manually enabling LoRA parameters...")
    for name, param in model.named_parameters():
        if 'lora' in name.lower():
            param.requires_grad = True
            #print(f"Enabled: {name}")

    trainable_params = [p for p in model.parameters() if p.requires_grad]
    print(f"After manual enabling: {len(trainable_params)} trainable parameters")

if len(trainable_params) > 0:
    optimizer = AdamW(trainable_params, lr=5e-5)
    print("✓ Optimizer created successfully")
else:
    print("❌ Still no trainable parameters found!")

=== LOADING FROM CHECKPOINT: imb_tuning/ex4/checkpoint-epoch29-wer0.7532-mer0.6842-1754437771 ===
Available adapters: dict_keys(['default'])
Active adapter: default
✓ Successfully loaded model and processor from checkpoint
Found 0 trainable parameters
No trainable parameters found, manually enabling LoRA parameters...
After manual enabling: 96 trainable parameters
✓ Optimizer created successfully

In [ ]:
data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor)

In [8]:
import jiwer

# LoRA training

LoRA training: the explicit training set example

In [45]:
from torch.utils.data import DataLoader
from torch.utils.data import DataLoader
from torch.optim import AdamW
from transformers import get_scheduler
import torch
import numpy as np
import os
import shutil
import time
from tqdm.auto import tqdm
from torch import device
best_wer = float("inf")
best_mer_at_best_wer = float("inf")  # MER corresponding to best WER
best_model_dir = None
base_dir = "imb_tuning/ex4"

data_collator = DataCollatorSpeechSeq2SeqWithPadding()
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True, collate_fn=data_collator)
val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False, collate_fn=data_collator)
device = torch.device("mps")
num_epochs = 50
#trainable_params = [p for p in model.parameters() if p.requires_grad]
#optimizer = AdamW(trainable_params, lr=5e-5)
num_training_steps = num_epochs * len(train_loader)
lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=500,
    num_training_steps=num_training_steps,
)
for epoch in range(num_epochs):
    model.train()
    total_loss = 0.0
    print(f"\nEpoch {epoch+1}/{num_epochs}")

    for step, batch in enumerate(tqdm(train_loader, desc=f"Training Epoch {epoch+17}")):
        # Only print batch keys for first batch to avoid cluttering output
        if step == 0:
            print("Batch keys:", batch.keys())
        batch = {k: v.to(device) for k, v in batch.items()}

        # Access the underlying Speech2Text model through LoRA wrapper
        outputs = model.base_model.model(
            input_features=batch["input_features"],
            labels=batch["labels"],
        )

        loss = outputs.loss
        if not torch.isfinite(loss):
            print(f"Warning: Non-finite loss at step {step}, skipping batch")
            optimizer.zero_grad()
            continue

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        total_loss += loss.item()

    avg_train_loss = total_loss / len(train_loader)
    print(f"Avg training loss: {avg_train_loss:.4f}")

    # Validation
    model.eval()
    val_loss = 0

    with torch.no_grad():
        for batch in tqdm(val_loader, desc=f"Validation Epoch {epoch+1}"):
            batch = {k: v.to(device) for k, v in batch.items()}

            # Access the underlying model for validation too
            outputs = model.base_model.model(
                input_features=batch["input_features"],
                labels=batch["labels"],
            )
            val_loss += outputs.loss.item()

    avg_val_loss = val_loss / len(val_loader)
    print(f"Validation loss: {avg_val_loss:.4f}")

    # Generation for WER calculation
    all_preds = []
    all_refs = []

    for batch in tqdm(val_loader, desc="Generating predictions"):
        batch = {k: v.to(device) for k, v in batch.items()}

        with torch.no_grad():
            # For generation, use the full model but with correct parameters
            generated_ids = model.generate(
                input_features=batch["input_features"],
                max_length=128,
                num_beams=4,
                early_stopping=True,
            )

            preds = processor.batch_decode(generated_ids, skip_special_tokens=True)
            labels = batch["labels"].cpu().numpy()
            labels = np.where(labels == -100, processor.tokenizer.pad_token_id, labels)
            refs = processor.batch_decode(labels, skip_special_tokens=True)

            all_preds.extend(preds)
            all_refs.extend(refs)

    # Compute both WER and MER using jiwer
    wer = jiwer.wer(all_refs, all_preds)
    mer = jiwer.mer(all_refs, all_preds)
    print(f"Validation WER: {wer:.4f}")
    print(f"Validation MER: {mer:.4f}")
    print(f"Current best WER: {best_wer:.4f} (MER at best WER: {best_mer_at_best_wer:.4f})")

    # Save best model based on WER and record corresponding MER
    if wer < best_wer:
        if best_model_dir and os.path.exists(best_model_dir):
            shutil.rmtree(best_model_dir)

        best_wer = wer
        best_mer_at_best_wer = mer  # Record MER at the point of best WER
        timestamp = int(time.time())
        best_model_dir = os.path.join(base_dir, f"checkpoint-epoch{epoch+1}-wer{wer:.4f}-mer{mer:.4f}-{timestamp}")
        os.makedirs(best_model_dir, exist_ok=True)

        model.save_pretrained(best_model_dir, safe_serialization=True)
        processor.save_pretrained(best_model_dir)
        print(f"Saved LoRA adapter and processor to {best_model_dir}")
        print(f"New best WER: {best_wer:.4f} with corresponding MER: {best_mer_at_best_wer:.4f}")

# Training complete - print final best metrics
print(f"\n=== Training Complete ===")
print(f"Final best WER: {best_wer:.4f}")
print(f"MER at best WER checkpoint: {best_mer_at_best_wer:.4f}")
print(f"Best model saved at: {best_model_dir}")

Epoch 1/50

Training Epoch 17:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.5793

Validation Epoch 1:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.9033

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7914
Validation MER: 0.7141
Current best WER: inf (MER at best WER: inf)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch1-wer0.7914-mer0.7141-1754433715
New best WER: 0.7914 with corresponding MER: 0.7141

Epoch 2/50

Training Epoch 18:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.5472

Validation Epoch 2:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.8736

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7909
Validation MER: 0.7083
Current best WER: 0.7914 (MER at best WER: 0.7141)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch2-wer0.7909-mer0.7083-1754433882
New best WER: 0.7909 with corresponding MER: 0.7083

Epoch 3/50

Training Epoch 19:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.4837

Validation Epoch 3:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.8405

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7831
Validation MER: 0.7029
Current best WER: 0.7909 (MER at best WER: 0.7083)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch3-wer0.7831-mer0.7029-1754433983
New best WER: 0.7831 with corresponding MER: 0.7029

Epoch 4/50

Training Epoch 20:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.4562

Validation Epoch 4:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7961

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7733
Validation MER: 0.6956
Current best WER: 0.7831 (MER at best WER: 0.7029)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch4-wer0.7733-mer0.6956-1754434236
New best WER: 0.7733 with corresponding MER: 0.6956

Epoch 5/50

Training Epoch 21:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.4063

Validation Epoch 5:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7820

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7713
Validation MER: 0.6972
Current best WER: 0.7733 (MER at best WER: 0.6956)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch5-wer0.7713-mer0.6972-1754434371
New best WER: 0.7713 with corresponding MER: 0.6972

Epoch 6/50

Training Epoch 22:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.3837

Validation Epoch 6:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7738

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7708
Validation MER: 0.6968
Current best WER: 0.7713 (MER at best WER: 0.6972)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch6-wer0.7708-mer0.6968-1754434499
New best WER: 0.7708 with corresponding MER: 0.6968

Epoch 7/50

Training Epoch 23:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.3748

Validation Epoch 7:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7639

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7664
Validation MER: 0.6952
Current best WER: 0.7708 (MER at best WER: 0.6968)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch7-wer0.7664-mer0.6952-1754434596
New best WER: 0.7664 with corresponding MER: 0.6952

Epoch 8/50

Training Epoch 24:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.3483

Validation Epoch 8:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7502

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7689
Validation MER: 0.6944
Current best WER: 0.7664 (MER at best WER: 0.6952)

Epoch 9/50

Training Epoch 25:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.3209

Validation Epoch 9:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7435

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7728
Validation MER: 0.6967
Current best WER: 0.7664 (MER at best WER: 0.6952)

Epoch 10/50

Training Epoch 26:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.2878

Validation Epoch 10:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7263

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7782
Validation MER: 0.6963
Current best WER: 0.7664 (MER at best WER: 0.6952)

Epoch 11/50

Training Epoch 27:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.2699

Validation Epoch 11:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7201

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7644
Validation MER: 0.6922
Current best WER: 0.7664 (MER at best WER: 0.6952)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch11-wer0.7644-mer0.6922-1754435191
New best WER: 0.7644 with corresponding MER: 0.6922

Epoch 12/50

Training Epoch 28:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.2613

Validation Epoch 12:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.7097

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7698
Validation MER: 0.6931
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 13/50

Training Epoch 29:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.2272

Validation Epoch 13:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6999

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7713
Validation MER: 0.6941
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 14/50

Training Epoch 30:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.2351

Validation Epoch 14:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6845

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7674
Validation MER: 0.6921
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 15/50

Training Epoch 31:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.2164

Validation Epoch 15:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6873

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7723
Validation MER: 0.6959
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 16/50

Training Epoch 32:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1913

Validation Epoch 16:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6822

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7728
Validation MER: 0.6961
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 17/50

Training Epoch 33:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1921

Validation Epoch 17:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6771

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7723
Validation MER: 0.6944
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 18/50

Training Epoch 34:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1647

Validation Epoch 18:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6665

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7718
Validation MER: 0.6955
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 19/50

Training Epoch 35:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1567

Validation Epoch 19:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6678

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7708
Validation MER: 0.6949
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 20/50

Training Epoch 36:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1670

Validation Epoch 20:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6627

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7664
Validation MER: 0.6916
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 21/50

Training Epoch 37:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1376

Validation Epoch 21:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6632

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7644
Validation MER: 0.6880
Current best WER: 0.7644 (MER at best WER: 0.6922)

Epoch 22/50

Training Epoch 38:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1435

Validation Epoch 22:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6553

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7630
Validation MER: 0.6882
Current best WER: 0.7644 (MER at best WER: 0.6922)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch22-wer0.7630-mer0.6882-1754437045
New best WER: 0.7630 with corresponding MER: 0.6882

Epoch 23/50

Training Epoch 39:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1224

Validation Epoch 23:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6512

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7659
Validation MER: 0.6896
Current best WER: 0.7630 (MER at best WER: 0.6882)

Epoch 24/50

Training Epoch 40:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1258

Validation Epoch 24:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6424

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7586
Validation MER: 0.6894
Current best WER: 0.7630 (MER at best WER: 0.6882)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch24-wer0.7586-mer0.6894-1754437256
New best WER: 0.7586 with corresponding MER: 0.6894

Epoch 25/50

Training Epoch 41:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1021

Validation Epoch 25:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6455

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7571
Validation MER: 0.6880
Current best WER: 0.7586 (MER at best WER: 0.6894)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch25-wer0.7571-mer0.6880-1754437369
New best WER: 0.7571 with corresponding MER: 0.6880

Epoch 26/50

Training Epoch 42:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.1083

Validation Epoch 26:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6453

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7654
Validation MER: 0.6910
Current best WER: 0.7571 (MER at best WER: 0.6880)

Epoch 27/50

Training Epoch 43:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0979

Validation Epoch 27:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6366

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7561
Validation MER: 0.6868
Current best WER: 0.7571 (MER at best WER: 0.6880)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch27-wer0.7561-mer0.6868-1754437566
New best WER: 0.7561 with corresponding MER: 0.6868

Epoch 28/50

Training Epoch 44:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0880

Validation Epoch 28:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6379

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7581
Validation MER: 0.6886
Current best WER: 0.7561 (MER at best WER: 0.6868)

Epoch 29/50

Training Epoch 45:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0765

Validation Epoch 29:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6314

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7532
Validation MER: 0.6842
Current best WER: 0.7561 (MER at best WER: 0.6868)
Saved LoRA adapter and processor to imb_tuning/ex4/checkpoint-epoch29-wer0.7532-mer0.6842-1754437771
New best WER: 0.7532 with corresponding MER: 0.6842

Epoch 30/50

Training Epoch 46:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0699

Validation Epoch 30:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6300

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7556
Validation MER: 0.6858
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 31/50

Training Epoch 47:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0738

Validation Epoch 31:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6307

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7610
Validation MER: 0.6894
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 32/50

Training Epoch 48:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0536

Validation Epoch 32:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6281

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7684
Validation MER: 0.6921
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 33/50

Training Epoch 49:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0631

Validation Epoch 33:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6291

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7659
Validation MER: 0.6911
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 34/50

Training Epoch 50:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0498

Validation Epoch 34:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6287

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7679
Validation MER: 0.6911
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 35/50

Training Epoch 51:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0481

Validation Epoch 35:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6205

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7664
Validation MER: 0.6900
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 36/50

Training Epoch 52:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0623

Validation Epoch 36:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6165

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7649
Validation MER: 0.6890
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 37/50

Training Epoch 53:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0237

Validation Epoch 37:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6182

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7649
Validation MER: 0.6899
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 38/50

Training Epoch 54:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0354

Validation Epoch 38:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6173

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7649
Validation MER: 0.6887
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 39/50

Training Epoch 55:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0388

Validation Epoch 39:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6162

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7654
Validation MER: 0.6888
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 40/50

Training Epoch 56:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0314

Validation Epoch 40:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6180

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7644
Validation MER: 0.6883
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 41/50

Training Epoch 57:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0356

Validation Epoch 41:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6173

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7664
Validation MER: 0.6900
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 42/50

Training Epoch 58:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0328

Validation Epoch 42:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6162

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7674
Validation MER: 0.6900
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 43/50

Training Epoch 59:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0455

Validation Epoch 43:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6141

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7649
Validation MER: 0.6893
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 44/50

Training Epoch 60:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0304

Validation Epoch 44:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6165

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7635
Validation MER: 0.6877
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 45/50

Training Epoch 61:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0201

Validation Epoch 45:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6154

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7644
Validation MER: 0.6880
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 46/50

Training Epoch 62:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0233

Validation Epoch 46:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6156

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7669
Validation MER: 0.6902
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 47/50

Training Epoch 63:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0238

Validation Epoch 47:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6143

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7635
Validation MER: 0.6898
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 48/50

Training Epoch 64:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0115

Validation Epoch 48:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6148

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7640
Validation MER: 0.6903
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 49/50

Training Epoch 65:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0160

Validation Epoch 49:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6148

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7640
Validation MER: 0.6903
Current best WER: 0.7532 (MER at best WER: 0.6842)

Epoch 50/50

Training Epoch 66:   0%|          | 0/380 [00:00<?, ?it/s]

Batch keys: dict_keys(['input_features', 'labels'])
Avg training loss: 2.0186

Validation Epoch 50:   0%|          | 0/83 [00:00<?, ?it/s]

Validation loss: 2.6147

Generating predictions:   0%|          | 0/83 [00:00<?, ?it/s]

Validation WER: 0.7640
Validation MER: 0.6903
Current best WER: 0.7532 (MER at best WER: 0.6842)

=== Training Complete ===
Final best WER: 0.7532
MER at best WER checkpoint: 0.6842
Best model saved at: imb_tuning/ex4/checkpoint-epoch29-wer0.7532-mer0.6842-1754437771

# Evaluating on explicit test: LoRA model, trained on the explicit train set

In [ ]:
curses = {'fuck', 'shit', 'bitch', 'cock', 'faggot', 'cunt', 'pussy', 'dick','ass'}
model.eval()

PeftModelForSeq2SeqLM(
  (base_model): LoraModel(
    (model): Speech2TextForConditionalGeneration(
      (model): Speech2TextModel(
        (encoder): Speech2TextEncoder(
          (conv): Conv1dSubsampler(
            (conv_layers): ModuleList(
              (0): Conv1d(80, 1024, kernel_size=(5,), stride=(2,), padding=(2,))
              (1): Conv1d(512, 512, kernel_size=(5,), stride=(2,), padding=(2,))
            )
          )
          (embed_positions): Speech2TextSinusoidalPositionalEmbedding()
          (layers): ModuleList(
            (0-11): 12 x Speech2TextEncoderLayer(
              (self_attn): Speech2TextAttention(
                (k_proj): Linear(in_features=256, out_features=256, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=256, out_features=256, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=256, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=256, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=256, out_features=256, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=256, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=256, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=256, out_features=256, bias=True)
              )
              (self_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
              (activation_fn): ReLU()
              (fc1): Linear(in_features=256, out_features=2048, bias=True)
              (fc2): Linear(in_features=2048, out_features=256, bias=True)
              (final_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            )
          )
          (layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
        (decoder): Speech2TextDecoder(
          (embed_tokens): Embedding(10000, 256, padding_idx=1)
          (embed_positions): Speech2TextSinusoidalPositionalEmbedding()
          (layers): ModuleList(
            (0-5): 6 x Speech2TextDecoderLayer(
              (self_attn): Speech2TextAttention(
                (k_proj): Linear(in_features=256, out_features=256, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=256, out_features=256, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=256, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=256, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=256, out_features=256, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=256, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=256, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=256, out_features=256, bias=True)
              )
              (activation_fn): ReLU()
              (self_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
              (encoder_attn): Speech2TextAttention(
                (k_proj): Linear(in_features=256, out_features=256, bias=True)
                (v_proj): lora.Linear(
                  (base_layer): Linear(in_features=256, out_features=256, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=256, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=256, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (q_proj): lora.Linear(
                  (base_layer): Linear(in_features=256, out_features=256, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.1, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=256, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=256, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_proj): Linear(in_features=256, out_features=256, bias=True)
              )
              (encoder_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
              (fc1): Linear(in_features=256, out_features=2048, bias=True)
              (fc2): Linear(in_features=2048, out_features=256, bias=True)
              (final_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
            )
          )
          (layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
      (lm_head): Linear(in_features=256, out_features=10000, bias=False)
    )
  )
)

In [ ]:
test_path = "exp_test"

In [ ]:
df_all_results = curse_detections_one_set(test_path, model, processor, device, data_collator, curses)

  0%|          | 0/383 [00:00<?, ?it/s]`cache.key_cache[idx]` is deprecated and will be removed in v4.56.0. Use `cache.layers[idx].keys` instead.
`cache.value_cache[idx]` is deprecated and will be removed in v4.56.0. Use `cache.layers[idx].values` instead.
100%|██████████| 383/383 [01:52<00:00,  3.42it/s]

In [38]:
df_all_results

    set       WER       MER  precision    recall  accuracy        f1
0  test  0.713633  0.655844   0.638889  0.247312   0.78329  0.356589

# Evaluating on test: LoRA model, trained on the biggest train set

In [63]:
import torch

# Clear MPS cache
if torch.backends.mps.is_available():
    torch.mps.empty_cache()
    
# You can also check memory usage
print(f"MPS allocated: {torch.mps.current_allocated_memory() / 1024**2:.2f} MB")
print(f"MPS reserved: {torch.mps.driver_allocated_memory() / 1024**2:.2f} MB")

MPS allocated: 222.03 MB
MPS reserved: 542.31 MB

## Evaluation functions

In [ ]:
import pandas as pd
import re
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score

def evaluate_curse_detection(df, curses, case_insensitive=True):
    """
    df: pandas DataFrame with columns 'reference' and 'prediction'
    curses: list of curse words (strings or regex patterns)
    """
    if case_insensitive:
        curses = [c.lower() for c in curses]

    def contains_curse(text):
        if not isinstance(text, str):  # Handle NaNs or missing text
            return False
        text = text.lower() if case_insensitive else text
        return any(re.search(rf'\b{re.escape(c)}\b', text) for c in curses)

    # Compute boolean flags
    df["label_has_curse"] = df["reference"].apply(contains_curse)
    df["pred_has_curse"] = df["prediction"].apply(contains_curse)

    # Extract ground truth and predictions
    y_true = df["label_has_curse"]
    y_pred = df["pred_has_curse"]

    # Compute metrics
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    accuracy = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true,y_pred)
    # Return results and annotated DataFrame
    return {
        "precision": precision,
        "recall": recall,
        "accuracy": accuracy,
        "f1": f1
    }

In [14]:
import torch
from torch.utils.data import DataLoader
import pandas as pd
from tqdm import tqdm
#import evaluate
import numpy as np
from datasets import load_from_disk


def run_eval_on_dataset(dataset, model, processor, device, data_collator, batch_size=1, seed=42):
    model.eval()
    all_preds = []
    all_refs = []

    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False, collate_fn=data_collator)

    for batch in tqdm(loader):
        batch = {k: v.to(device) for k, v in batch.items()}
        with torch.no_grad():
            generated_ids = model.generate(
                input_features=batch["input_features"],
                attention_mask=batch.get("attention_mask", None),
                max_length=128,
                num_beams=4,
                early_stopping=True,
            )

        preds = processor.batch_decode(generated_ids, skip_special_tokens=True)
        labels = batch["labels"].cpu().numpy()
        labels = np.where(labels == -100, processor.tokenizer.pad_token_id, labels)
        refs = processor.batch_decode(labels, skip_special_tokens=True)

        all_preds.extend(preds)
        all_refs.extend(refs)

    return all_preds, all_refs


def curse_detections_all_sets(train_path, val_path, test_path, model, processor, device, data_collator, curses, seed=42):
    results = []

    for name, path in [("train", train_path), ("validation", val_path), ("test", test_path)]:
        dataset = load_from_disk(path)
        preds, refs = run_eval_on_dataset(dataset, model, processor, device, data_collator)

        wer = jiwer.wer(preds, refs)
        mer = jiwer.mer(preds, refs)
       # wer = wer_metric.compute(predictions=preds, references=refs)

        df = pd.DataFrame({"reference": refs, "prediction": preds})
        curse_metrics = evaluate_curse_detection(df, curses)

        results.append({
            "set": name,
            "WER": wer,
            'MER': mer,
            **curse_metrics
        })

    return pd.DataFrame(results)


def curse_detections_one_set(test_path, model, processor, device, data_collator, curses, seed=42):
    results = []

    for name, path in [("test", test_path)]:
        dataset = load_from_disk(path)
        preds, refs = run_eval_on_dataset(dataset, model, processor, device, data_collator)

        wer = jiwer.wer(preds, refs)
        mer = jiwer.mer(preds, refs)
       # wer = wer_metric.compute(predictions=preds, references=refs)

        df = pd.DataFrame({"reference": refs, "prediction": preds})
        curse_metrics = evaluate_curse_detection(df, curses)

        results.append({
            "set": name,
            "WER": wer,
            'MER': mer,
            **curse_metrics
        })

    return pd.DataFrame(results)

In [ ]:
test_path = "biggest_test"

In [ ]:
df_all_results = curse_detections_one_set(test_path, model, processor, device, data_collator, curses)

100%|██████████| 22984/22984 [19:16:07<00:00,  3.02s/it]

In [80]:
df_all_results

    set       WER       MER  precision    recall  accuracy        f1
0  test  0.623327  0.581479   0.266667  0.043011  0.995649  0.074074

# Evaluating on test: untrained librispeech (baseline)

In [1]:
test_path = "biggest_test"

In [4]:
from transformers import Speech2TextForConditionalGeneration, Speech2TextProcessor
  
    
model = Speech2TextForConditionalGeneration.from_pretrained("facebook/s2t-small-librispeech-asr")
processor = Speech2TextProcessor.from_pretrained("facebook/s2t-small-librispeech-asr")

In [8]:
device = "cuda" if torch.cuda.is_available() else "mps"
model.to(device)

Speech2TextForConditionalGeneration(
  (model): Speech2TextModel(
    (encoder): Speech2TextEncoder(
      (conv): Conv1dSubsampler(
        (conv_layers): ModuleList(
          (0): Conv1d(80, 1024, kernel_size=(5,), stride=(2,), padding=(2,))
          (1): Conv1d(512, 512, kernel_size=(5,), stride=(2,), padding=(2,))
        )
      )
      (embed_positions): Speech2TextSinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x Speech2TextEncoderLayer(
          (self_attn): Speech2TextAttention(
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (out_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=256, out_features=2048, bias=True)
          (fc2): Linear(in_features=2048, out_features=256, bias=True)
          (final_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): Speech2TextDecoder(
      (embed_tokens): Embedding(10000, 256, padding_idx=1)
      (embed_positions): Speech2TextSinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-5): 6 x Speech2TextDecoderLayer(
          (self_attn): Speech2TextAttention(
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (out_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): Speech2TextAttention(
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (out_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=256, out_features=2048, bias=True)
          (fc2): Linear(in_features=2048, out_features=256, bias=True)
          (final_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=256, out_features=10000, bias=False)
)

In [9]:
model.eval()

Speech2TextForConditionalGeneration(
  (model): Speech2TextModel(
    (encoder): Speech2TextEncoder(
      (conv): Conv1dSubsampler(
        (conv_layers): ModuleList(
          (0): Conv1d(80, 1024, kernel_size=(5,), stride=(2,), padding=(2,))
          (1): Conv1d(512, 512, kernel_size=(5,), stride=(2,), padding=(2,))
        )
      )
      (embed_positions): Speech2TextSinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x Speech2TextEncoderLayer(
          (self_attn): Speech2TextAttention(
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (out_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=256, out_features=2048, bias=True)
          (fc2): Linear(in_features=2048, out_features=256, bias=True)
          (final_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): Speech2TextDecoder(
      (embed_tokens): Embedding(10000, 256, padding_idx=1)
      (embed_positions): Speech2TextSinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-5): 6 x Speech2TextDecoderLayer(
          (self_attn): Speech2TextAttention(
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (out_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): Speech2TextAttention(
            (k_proj): Linear(in_features=256, out_features=256, bias=True)
            (v_proj): Linear(in_features=256, out_features=256, bias=True)
            (q_proj): Linear(in_features=256, out_features=256, bias=True)
            (out_proj): Linear(in_features=256, out_features=256, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=256, out_features=2048, bias=True)
          (fc2): Linear(in_features=2048, out_features=256, bias=True)
          (final_layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=256, out_features=10000, bias=False)
)

In [ ]:
data_collator = DataCollatorSpeechSeq2SeqWithPadding()

In [16]:
import re
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score

df_all_results = curse_detections_one_set(test_path, model, processor, device, data_collator, curses)

100%|██████████| 22984/22984 [1:23:00<00:00,  4.61it/s]

In [17]:
df_all_results

    set       WER       MER  precision    recall  accuracy        f1
0  test  0.920579  0.839861        0.1  0.021505  0.995258  0.035398